services:
  clubnikka-db:
    env_file: .env
    image: postgres:latest
    container_name: clubnikka-db
    volumes:
      - postgres_data:/var/lib/postgres
    restart: unless-stopped

    user: ${DB_USER}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
